kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
metadata:
  name: cluster-controlplane
spec:
  replicas: 3
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 0
    type: RollingUpdate