- op: add
  path: "/spec/kubeadmConfigSpec/files/-"
  value:
    path: /etc/keepalived/keepalived.conf
    content: |
         ! Configuration File for keepalived
         global_defs {
         }
         vrrp_script check_apiserver {
           script "/etc/keepalived/check_apiserver.sh"
           interval 3
           weight -2
           fall 10
           rise 2
         }
         vrrp_instance KUBERNETES {
             state BACKUP
             interface REPLACEMENT_INTERFACE_1
             virtual_router_id 101
             priority 101
             advert_int 1
             virtual_ipaddress {
                REPLACEMENT_VIP_1
             }
             track_script {
              check_apiserver
             }
         }
- op: add
  path: "/spec/kubeadmConfigSpec/files/-"
  value:
    path: /etc/keepalived/check_apiserver.sh
    content: |
         #!/bin/sh
         errorExit() {
             echo "*** $*" 1>&2
             exit 1
         }
         curl --silent --max-time 2 --insecure https://localhost:6443/ -o /dev/null || errorExit "Error GET https://localhost:6443/"
         if ip addr | grep -q "10.23.25.180"; then
             curl --silent --max-time 2 --insecure https://10.23.25.180:6443/ -o /dev/null || errorExit "Error GET https://10.23.25.180:6443/"
         fi
- op: add
  path: "/spec/kubeadmConfigSpec/preKubeadmCommands/-"
  value:
      chmod a+x /etc/keepalived/check_apiserver.sh
- op: add
  path: "/spec/kubeadmConfigSpec/preKubeadmCommands/-"
  value:
      # Please note the a list of string get appended.It is better to
      # add one item at a time using op: add
      systemctl enable --now keepalived
- op: add
  path: "/spec/kubeadmConfigSpec/preKubeadmCommands/-"
  value:
      systemctl restart keepalived